services:
  - type: web
    name: inventory-agent-app
    env: python
    buildCommand: ""
    startCommand: streamlit run app.py --server.port $PORT
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false